"""empty message

Revision ID: 545635b415a2
Revises: b62f8718530c
Create Date: 2023-10-17 14:21:05.942697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545635b415a2'
down_revision = 'b62f8718530c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_taco_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_taco_favorites', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
