"""empty message

Revision ID: b62f8718530c
Revises: 2201e2537b5c
Create Date: 2023-10-17 12:33:08.295704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62f8718530c'
down_revision = '2201e2537b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_taco_favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('taco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taco_id'], ['tacos.id'], name=op.f('fk_user_taco_favorites_taco_id_tacos')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_taco_favorites_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_taco_favorites')
    # ### end Alembic commands ###
